### ISSUE TITLE
How do  I input in the feild?

### ISSUE THREAD

**Issue by thisisbipin** [xianzhon/vim-code-runner#1]
I was trying to run my code, using this plugin, but I am not able to enter the command in the window which gets popped for showing output...
can this feature be added?
![image](https://user-images.githubusercontent.com/55138889/118285488-1f491a00-b4ef-11eb-8a10-44ad85b3a170.png)

**Comment by xianzhon** [comment]
@thisisbipin Hi, thank you for using this plugin and sorry for late reply.

As below PR merged, this plugin supports the user inputs in the output window. (Thanks for @Borwe 's contribution!)
https://github.com/xianzhon/vim-code-runner/pull/3

**Comment by thisisbipin** [comment]
Yeah! Thanks for adding the feature... Your plugin is very useful! 😄
